<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../ELKA.PowerThrottleControl/Services/UpdateService.cs" Link="UpdateService.cs" />
    <Compile Include="../../ELKA.PowerThrottleControl/Services/UpdateLauncher.cs" Link="UpdateLauncher.cs" />
  </ItemGroup>
</Project>
