<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\ELKA.PowerThrottleControl.ico</ApplicationIcon>
    <AssemblyName>ELKA.PowerThrottleControl</AssemblyName>
    <RootNamespace>ELKA.PowerThrottleControl</RootNamespace>
    <Product>ELKA Power Throttle Control</Product>
    <AssemblyTitle>ELKA Power Throttle Control</AssemblyTitle>
    <Company>ElkaSoft</Company>
    <Authors>ElkaSoft</Authors>
    <Description>Manage Windows per-application power throttling and general application firewall access and dedicated VB-Audio setup through a focused desktop interface.</Description>
    <Version>1.2.0</Version>
    <FileVersion>1.2.0.0</FileVersion>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <RepositoryUrl>https://github.com/torment78/ELKA.PowerThrottleControl</RepositoryUrl>
  </PropertyGroup>

</Project>
